### ISSUE TITLE
Add mode to allow fine-tuning of left/right position.

### ISSUE THREAD

**Issue by BrownGenius** [BHSRobotix/ChargedUp2023#126]
When aligning with the score, the current left/right controls don't provide enough precision.  The drive team requested that we have a "Scoring Alignment" mode that will reduce sensitivity of the drivetrain joystick controls.

**Comment by BrownGenius** [comment]
May not be needed after removing rotation slew rate limiter

**Comment by ParkerMeyers** [comment]
@adipraj17 Do you still need this?

**Comment by ParkerMeyers** [comment]
> If you can do it quickly then it would be useful otherwise it's fine. It should be a toggle on R2

Alright I can do it quickly.

**Comment by BrownGenius** [comment]
Resolved in #136 #142 #152
