### ISSUE TITLE
Link cone and cube buttons to cone and cube buttons in shuffleboard

### ISSUE THREAD

**Issue by ParkerMeyers** [BHSRobotix/ChargedUp2023#134]

**Comment by ParkerMeyers** [comment]
Also we need to add the OFF mode to the buttons

**Comment by BrownGenius** [comment]
How critical is this for competition?  I was thinking about getting rid of the Cone/Cube in the shuffleboard altogether because we can only score Cone in autonomous, anyway.

**Comment by ParkerMeyers** [comment]
It wasnt for autonomous, its for teleop/the assistant driver to click the buttons on shuffleboard

**Comment by BrownGenius** [comment]
The existing cone/cube buttons were meant for autonomous, but it's fine if we want to use it for teleop.  I think this is something you should work on.

**Comment by ParkerMeyers** [comment]
We've been using it for teleop, for the LEDs for arnesth
