### ISSUE TITLE
PID based drive

### ISSUE THREAD

**Issue by ParkerMeyers** [BHSRobotix/ChargedUp2023#27]
*Voltage

**Comment by ParkerMeyers** [comment]
Need to run SYSID on the chasis,
will do next meeting

**Comment by BrownGenius** [comment]
@ParkerMeyers, if you weren't already planning for using "[feedForward + pidControl](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/controllers/combining-feedforward-feedback.html)", I think we should.

**Comment by ParkerMeyers** [comment]
that is the plan yes, check the branch, I already did.

**Comment by BrownGenius** [comment]
Hi Parker, I took a quick look at your branch.  I know it's a WIP, but there isn't a need to expose odometry to the rest of the system.  Instead of calling "drive.updateOdometry()" from Robot.java, you can just call "updateOdometry()" from inside the DriveTrain subsystem's periodic() call.

**Comment by ParkerMeyers** [comment]
Yeah, I noticed that, that is the plan. It was formatted with this public update function in the example.
