### ISSUE TITLE
SYSID (Drivetrain)

### ISSUE THREAD

**Issue by ParkerMeyers** [BHSRobotix/ChargedUp2023#41]
Sysid & 2 different pid loops for different sides of the robot using constants

**Comment by BrownGenius** [comment]
@ParkerMeyers, we will likely need to invert encoders in the sysId config in order to get positive distance readings when moving forward. See #53.

![image](https://user-images.githubusercontent.com/49494444/218263999-ed944fc8-8d25-41ce-8a83-332d19e1d63c.png)

**Comment by BrownGenius** [comment]
Completed
